### ISSUE TITLE
5k权重不匹配

### ISSUE THREAD

**Issue by ycwsilent** [DeniJsonC/WaveNet#17]
在运行demo时候，加载5k的权重，但是是运行不起来，
运行命令为
```
python demo.py --input_dir ../datasets/FiveK/test/low --result_dir ./visual/FiveK/B1 --weights ../checkpoints/5k/W
aveNet_B_5k.pth
```
报错为如下;感觉就是问题2一样
```
RuntimeError: Error(s) in loading state_dict for WaveNet:
        Missing key(s) in state_dict: "asff.fcs.0.0.weight", "asff.fcs.0.1.weight", "asff.fcs.1.0.weight", "asff.fcs.1.1.weight", "asff.conv.weight".

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 252, in <module>
    load_checkpoint(model, args.weights, device)
  File "demo.py", line 226, in load_checkpoint
    state_dict = checkpoint["state_dict"]
KeyError: 'state_dict'
```
是有什么地方不对吗

**Comment by DeniJsonC** [comment]
> 在运行demo时候，加载5k的权重，但是是运行不起来， 运行命令为
> 
> ```
> python demo.py --input_dir ../datasets/FiveK/test/low --result_dir ./visual/FiveK/B1 --weights ../checkpoints/5k/W
> aveNet_B_5k.pth
> ```
> 
> 报错为如下;感觉就是问题2一样
> 
> ```
> RuntimeError: Error(s) in loading state_dict for WaveNet:
>         Missing key(s) in state_dict: "asff.fcs.0.0.weight", "asff.fcs.0.1.weight", "asff.fcs.1.0.weight", "asff.fcs.1.1.weight", "asff.conv.weight".
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "demo.py", line 252, in <module>
>     load_checkpoint(model, args.weights, device)
>   File "demo.py", line 226, in load_checkpoint
>     state_dict = checkpoint["state_dict"]
> KeyError: 'state_dict'
> ```
> 
> 是有什么地方不对吗

你好，加载WaveNet_B_5k权重，需在WaveNet_B模型参数里设置use_asff:False.

**Comment by ycwsilent** [comment]
您好，感谢您的回复；好像和问题9一样，但是我修改之后，它会报错什么尺寸不一样
修改
![image](https://github.com/user-attachments/assets/28985b9b-37ca-42ab-a780-36eedcd117d0)

运行
```
python demo.py --input_dir ../datasets/FiveK/test/low --result_dir ./visual/FiveK/B1 --weights ../checkpoints/5k/W
aveNet_B_5k.pth
```
报错
```
D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:235: UserWarning: Overwriting WaveNet_T in registry with models.archs.WaveNet_arch.WaveNet_T. This is
 because the name being registered conflicts with an existing name. Please check if this is not expected.
  def WaveNet_T(pretrained=False, **kwargs):
D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:249: UserWarning: Overwriting WaveNet_S in registry with models.archs.WaveNet_arch.WaveNet_S. This is
 because the name being registered conflicts with an existing name. Please check if this is not expected.
  def WaveNet_S(pretrained=False, **kwargs):
D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:263: UserWarning: Overwriting WaveNet_B in registry with models.archs.WaveNet_arch.WaveNet_B. This is
 because the name being registered conflicts with an existing name. Please check if this is not expected.
  def WaveNet_B(pretrained=False, **kwargs):
==> Build the model
enhancing images......
Traceback (most recent call last):
  File "demo.py", line 272, in <module>
    retored = model(restored.cuda())
  File "D:\Ananconda\envs\Retinexformer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 225, in forward
    embed_x = self.forward_tokens(conv_1x)
  File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 216, in forward_tokens
    x= block(x,enc_maps[i])
  File "D:\Ananconda\envs\Retinexformer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
    return forward_call(*input, **kwargs)
  File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 148, in forward
    x=self.up(x)+y
RuntimeError: The size of tensor a (764) must match the size of tensor b (765) at non-singleton dimension 3
```
这个有办法解决吗

**Comment by DeniJsonC** [comment]
> 您好，感谢您的回复；好像和问题9一样，但是我修改之后，它会报错什么尺寸不一样 修改 ![image](https://private-user-images.githubusercontent.com/171780109/349507759-28985b9b-37ca-42ab-a780-36eedcd117d0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEyMjE3OTQsIm5iZiI6MTcyMTIyMTQ5NCwicGF0aCI6Ii8xNzE3ODAxMDkvMzQ5NTA3NzU5LTI4OTg1YjliLTM3Y2EtNDJhYi1hNzgwLTM2ZWVkY2QxMTdkMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxN1QxMzA0NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NjNlOGVmODZjYmQzZWQzZTFmMDRmNGZkMDk4YTc4NDU4MmYyZDljOWM3ZmJiMWZlYmE3ZDA5OTU3N2EyMDVjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nEYLslYfAEZe7pAl-4vKA-0Fxr8lSJHt6_JwrV4sx8M)
> 
> 运行
> 
> ```
> python demo.py --input_dir ../datasets/FiveK/test/low --result_dir ./visual/FiveK/B1 --weights ../checkpoints/5k/W
> aveNet_B_5k.pth
> ```
> 
> 报错
> 
> ```
> D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:235: UserWarning: Overwriting WaveNet_T in registry with models.archs.WaveNet_arch.WaveNet_T. This is
>  because the name being registered conflicts with an existing name. Please check if this is not expected.
>   def WaveNet_T(pretrained=False, **kwargs):
> D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:249: UserWarning: Overwriting WaveNet_S in registry with models.archs.WaveNet_arch.WaveNet_S. This is
>  because the name being registered conflicts with an existing name. Please check if this is not expected.
>   def WaveNet_S(pretrained=False, **kwargs):
> D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py:263: UserWarning: Overwriting WaveNet_B in registry with models.archs.WaveNet_arch.WaveNet_B. This is
>  because the name being registered conflicts with an existing name. Please check if this is not expected.
>   def WaveNet_B(pretrained=False, **kwargs):
> ==> Build the model
> enhancing images......
> Traceback (most recent call last):
>   File "demo.py", line 272, in <module>
>     retored = model(restored.cuda())
>   File "D:\Ananconda\envs\Retinexformer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 225, in forward
>     embed_x = self.forward_tokens(conv_1x)
>   File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 216, in forward_tokens
>     x= block(x,enc_maps[i])
>   File "D:\Ananconda\envs\Retinexformer\lib\site-packages\torch\nn\modules\module.py", line 1110, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "D:\yan\WaveNet-1\basicsr\models\archs\WaveNet_arch.py", line 148, in forward
>     x=self.up(x)+y
> RuntimeError: The size of tensor a (764) must match the size of tensor b (765) at non-singleton dimension 3
> ```
> 
> 这个有办法解决吗

这是因为上下采样造成的大小不一致，你在demo.py文件里 取消注释 102 和113行，并注释掉114行即可。

**Comment by ycwsilent** [comment]
好的；可以了，相当感谢作者耐心的回复；；我还有一个不太恰当的问题，我用单张3090和你yml一样的设置，在训练lol这个数据集时候和你25.4左右的结果差很大，我只有22.8左右，这个应该是我哪里操作有问题吗？
下面这个是配置文件
```
# general settings
name: WaveNet_B_LOL
model_type: ImageCleanModel
scale: 1
num_gpu: 1  # set num_gpu: 0 for cpu mode
manual_seed: 5

# dataset and data loader settings
#### datasets
datasets:
  train:
    name: TrainSet
    type: Dataset_PairedImage
    dataroot_gt: /data/coding/WaveNet/datasets/LOL/train/high/
    dataroot_lq: /data/coding/WaveNet/datasets/LOL/train/low
    geometric_augs: true

    filename_tmpl: '{}'
    io_backend:
      type: disk

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 8

    GT_size: 256     # size you want to crop out as input sample.
    LQ_size: 256
    use_flip: false
    use_rot: false
    color: RGB


    ### -------------Multi-scale Training Strategy--------------------------
    batch_sizes: [1,1,1,2]             # Batch size per gpu   
    min_patch_size: 192
    step: 3
    sort: 0 #1 represents descending and 0 represents ascending
    stride: 32
    patience: 19
    state: 1 # 0 means start with crop 1 means start with resize
    ### ------------------------------------------------------------

    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: ValSet
    type: Dataset_PairedImage
    dataroot_gt: /data/coding/WaveNet/datasets/LOL/test/high/
    dataroot_lq: /data/coding/WaveNet/datasets/LOL/test/low/
    io_backend:
      type: disk
    val_crop: 


# network structures
network_g:
  type: WaveNet_B


# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  total_epochs: 1000
  total_iter: 145000
  warmup_iter: -1 # no warm up
  use_grad_clip: true

  # Split 300k iterations into two cycles. 
  # 1st cycle: fixed 3e-4 LR for 92k iters. 
  # 2nd cycle: cosine annealing (3e-4 to 1e-6) for 208k iters.
  scheduler:
    type: CosineAnnealingRestartCyclicLR
    periods: [450, 550,1500]       
    restart_weights: [1,1]
    eta_mins: [0.000125,0.000001,0.000001]   
  
  mixing_augs:
    mixup: true
    mixup_beta: 1.2
    use_identity: true

  optim_g:
    type: AdamW
    lr: !!float 1.25e-4
    # weight_decay: !!float 1e-4
    betas: [0.9, 0.999]
  
  # losses
  pixel_opt:
    type: ULoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  window_size: 4
  val_freq: !!float 1e2
  save_img: false
  rgb2bgr: true
  use_image: false
  max_minibatch: 8
  val_crop:

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 100
  save_checkpoint_freq: !!float 1e2
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
dist_params:
  backend: nccl
  port: 29500
```
这个是我最终的结果
![image](https://github.com/user-attachments/assets/7aa144a5-3562-47d5-b599-67827e4d6c81)
相应的结果趋势图
![image](https://github.com/user-attachments/assets/0d663a20-49ea-467d-9809-8596fa334701)

您的训练日志
![image](https://github.com/user-attachments/assets/e4b57712-a893-454f-984f-a27c94a9c4f9)

它不单长得不一样，而且甚至图的个数不一样，请问一下，这个应该也是我什么地方操作有问题吧
特别感谢并期待您的回答
